### ISSUE TITLE
Rethinkdbdash logs

### ISSUE THREAD

**Issue by PymZoR** [buckless/Server#18]
It would be nice to have control over rethinkdbdash logs in order to have a consistent logging system.

**Comment by gjuchault** [comment]
RethinkDB does not provide so much log (what's thrown on the console). There is still `--log-file` option which defaults to `log_file` (you can check that file on `rethinkdb_data/log_file`).
The real log file should be the reql requests made by the API and theses are defaulted to the console. I'd create a new logger that outputs in a file

**Comment by gjuchault** [comment]
Fixed by #33
