### ISSUE TITLE
Allow an Article to be part of multiple categories

### ISSUE THREAD

**Issue by lonk** [buckless/Server#24]
Ce qui génère les onglets, ce sont les catégories. Le soucis, c'est que selon un point, tu peux vouloir avoir deux objets dans différentes catégories. Exemple: dans un bar à bière, la chouffe peut être dans un onglet "Bières", tandis que dans un stand bouffe/boisson ça peut être dans un onglet "Boissons".

**Comment by gjuchault** [comment]
Solved by #36
