### ISSUE TITLE
Create database on first run

### ISSUE THREAD

**Issue by PymZoR** [buckless/Server#42]
The database needs to be manually created when the server is run for the first time. 
Pretty annoying !

> [ERR] ReqlOpFailedError: Database `bucklessServer_example` does not exist in

**Comment by gjuchault** [comment]
Thinky ensures database
You can try to `npm run stopdb && npm run cleardb && npm run test`

This snippet will ensure the database exists which may be useful for non-thinky scripts
```
r.dbList().contains('bucklessServer_example')
  .do(function(databaseExists) {
    return r.branch(
      databaseExists,
      { created: 0 },
      r.dbCreate('bucklessServer_example')
    );
  }).run();
```
